---
- name: ensure presence of user {{ julie.username }}
  user:
    name: "{{ julie.username }}"
    uid: "{{ julie.uid }}"
    password: "{{ julie.upasswd }}"
    comment: "{{ julie.comment }}"
    shell: "{{ julie.shell }}"
    group: "{{ default_group.name }}"

- name: ensure presence of {{ julie.username }}'s ssh key
  authorized_key:
    user: "{{ julie.username }}"
    state: present
    key: "{{ julie.public_key }}"

- name: ensure presence of samba config folder
  file:
    path: /etc/samba
    state: directory
    mode: 0750
    owner: root
    group: root

- name: ensure presence of {{ julie.username }}'s samba config file
  copy:
    src: julie.smb.conf
    dest: /etc/samba/julie.smb.conf
    mode: 0640
    owner: root
    group: root

- name: ensure {{ julie.username }}'s time machine folder has approperiate permissions
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - "/home/julie/backups"
    - "/home/julie/backups/timemachine"

- name: os-specific tasks
  include: 'os-{{ ansible_distribution }}.yml'
