---
- name: ensure presence of user {{ rob.username }}
  user:
    name: "{{ rob.username }}"
    uid: "{{ rob.uid }}"
    password: "{{ rob.passwd }}"
    comment: "{{ rob.comment }}"
    shell: "{{ rob.shell }}"
    group: "{{ default_group.name }}"

- name: ensure presence of {{ rob.username }}'s ssh key
  authorized_key:
    user: "{{ rob.username }}"
    state: present
    key: "{{ lookup('file', '/Users/rob/.ssh/id_rsa.pub') }}"

- name: ensure presence of samba config folder
  file:
    path: /etc/samba
    state: directory
    mode: 0750
    owner: root
    group: root

- name: ensure presence of {{ rob.username }}'s samba config file
  copy:
    src: rob.smb.conf
    dest: /etc/samba/rob.smb.conf
    mode: 0640
    owner: root
    group: root

- name: ensure {{ rob.username }}'s time machine folder has approperiate permissions
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - "/home/rob/backups"
    - "/home/rob/backups/timemachine"

- name: os-specific tasks
  include: 'os-{{ ansible_distribution }}.yml'
